---
title: 保持游戏的趣味性（续）
actions: ['checkAnswer', 'hints']
requireLogin: true
material:
  editor:
    language: javascript
    startingCode:
        "test/CryptoZombies.js": |
            const CryptoZombies = artifacts.require("CryptoZombies");
            const utils = require("./helpers/utils");
            const zombieNames = ["Zombie 1", "Zombie 2"];
            contract("CryptoZombies", (accounts) => {
                let [alice, bob] = accounts;
                let contractInstance;
                beforeEach(async () => {
                    contractInstance = await CryptoZombies.new();
                });
                it("should be able to create a new zombie", async () => {
                    const result = await contractInstance.createRandomZombie(zombieNames[0], {from: alice});
                    assert.equal(result.receipt.status, true);
                    assert.equal(result.logs[0].args.name,zombieNames[0]);
                })
                it("should not allow two zombies", async () => {
                    // start here
                })
            })
        "test/helpers/utils.js": |
            async function shouldThrow(promise) {
              try {
                  await promise;
                 assert(true);
              }
              catch (err) {
                  return;
              }
            assert(false, "The contract did not throw.");

            }

            module.exports = {
              shouldThrow,
            };

    answer: >
        const CryptoZombies = artifacts.require("CryptoZombies");

        const utils = require("./helpers/utils");

        const zombieNames = ["Zombie 1", "Zombie 2"];

        contract("CryptoZombies", (accounts) => {
            let [alice, bob] = accounts;
            let contractInstance;
            beforeEach(async () => {
                contractInstance = await CryptoZombies.new();
            });
            it("should be able to create a new zombie", async () => {
                const result = await contractInstance.createRandomZombie(zombieNames[0], {from: alice});
                assert.equal(result.receipt.status, true);
                assert.equal(result.logs[0].args.name,zombieNames[0]);
            })
            it("should not allow two zombies", async () => {
                await contractInstance.createRandomZombie(zombieNames[0], {from: alice});
                await utils.shouldThrow(contractInstance.createRandomZombie(zombieNames[1], {from: alice}));
            })
        })
---

在这一章中，我们将填充第二个测试的主体。是这样:
- 首先，Alice 应该调用 `createRandomZombie` 并将它命名为 `zombieNames[0]`， 作为她第一个僵尸的名字。
- 接下来，Alice 应该尝试创建她的第二个僵尸。唯一不同的是，这次应该将僵尸名设置为 `zombieNames[1]`。
- 此时，我们期望合约`报错`。
- 由于我们的测试应该只在智能合约出错时通过，所以我们的逻辑看起来会有点不同。我们将需要封装第二个 `createRandomZombie` 函数调用内的一个 `try/catch` 块，如下:

```javascript
try {
    //try to create the second zombie
    await contractInstance.createRandomZombie(zombieNames[1], {from: alice});
    assert(true);
  }
  catch (err) {
    return;
  }
assert(false, "The contract did not throw.");
```
现在我们得到了想要的，对吧?

呃…… 就差一点点了。

为了保持测试整洁，我们将上面的代码移到了 `helpers/utils.js` 中，并将其导入到 “CryptoZombies.js”，像这样:

```javascript
const utils = require("./helpers/utils");
```

调用该函数的代码行是这样的:

```javascript
await utils.shouldThrow(myAwesomeContractInstance.myAwesomeFunction());
```

# 实战演习

前一章中，我们为第二个测试创建了一个空 shell。现在来填充吧。

1.  首先，让 Alice 创造她的第一个僵尸。将它命名为 `zombieNames[0]`，别忘记正确设置其主人。

2.  在 Alice 创建了她的第一个僵尸后，用 `createRandomZombie` 作为参数运行`shouldThrow`。如果不记得这个的语法，请查看上面的示例。但请先自己尝试，不要偷看哟。

太棒了，你刚刚已经完成了你的第二个测试！

现在，我们继续为你运行 `truffle test`。输出:

```bash
Contract: CryptoZombies
    ✓ should be able to create a new zombie (129ms)
    ✓ should not allow two zombies (148ms)


  2 passing (1s)
```

测试通过啦！ 欧耶!
